use_default_settings: true

server:
  base_url: "http://localhost:8080/"
  secret_key: "${SEARXNG_SECRET_KEY}"
  limiter: true
  image_proxy: true

redis:
  url: redis://valkey:6379/0

ui:
  default_theme: simple
  default_locale: ""

search:
  safe_search: 0
  default_lang: ""
  autocomplete: google
  formats:
    - html
    - json
